apiVersion: v1
kind: Service
metadata:
  name: action-runner
  namespace: action-runner
  labels:
    app.kubernetes.io/name: action-runner
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: action-runner
  ports:
    - name: http
      port: 8080
      targetPort: http
