apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zakharhome-site
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: zakharhome-site
    files:
      - src/index.html
      - src/nginx.conf

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: zakharhome-site
