apiVersion: apps/v1
kind: Deployment
metadata:
  name: clean-mail-frontend
  namespace: clean-mail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clean-mail-frontend
  template:
    metadata:
      labels:
        app: clean-mail-frontend
    spec:
      imagePullSecrets:
        - name: clean-mail-ghcr-pull
      containers:
        - name: frontend
          image: ghcr.io/mzakhar/clean-mail-frontend@sha256:3f4d2e4fc85e4869fe643623e6d2564736f02d48a8a8619268d5282380d9fcb7
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: clean-mail-frontend-svc
  namespace: clean-mail
spec:
  selector:
    app: clean-mail-frontend
  ports:
    - port: 80
      targetPort: 80
