apiVersion: apps/v1
kind: Deployment
metadata:
  name: clean-mail-frontend
  namespace: clean-mail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clean-mail-frontend
  template:
    metadata:
      labels:
        app: clean-mail-frontend
    spec:
      imagePullSecrets:
        - name: clean-mail-ghcr-pull
      containers:
        - name: frontend
          image: ghcr.io/mzakhar/clean-mail-frontend@sha256:b925dcf804470d78342f71c0b14874326c275ec43b69cab60feb115ae03cc25c
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: clean-mail-frontend-svc
  namespace: clean-mail
spec:
  selector:
    app: clean-mail-frontend
  ports:
    - port: 80
      targetPort: 80
